#!/bin/sh
set -eux

# Check that dbus-system-bus-common provides its intended interface.

test -f /usr/lib/systemd/system/dbus.socket
test -f /usr/share/dbus-1/system.conf
getent passwd messagebus
getent group messagebus
