debian/tmp/etc/dbus-1/
debian/tmp/bin/dbus-daemon
debian/tmp/bin/dbus-cleanup-sockets
debian/tmp/bin/dbus-send usr/bin
debian/tmp/bin/dbus-uuidgen
debian/tmp/bin/dbus-monitor usr/bin
debian/tmp/usr/lib/dbus-1.0/dbus-daemon-launch-helper
debian/tmp/usr/share/man/man1/dbus-daemon.1
debian/tmp/usr/share/man/man1/dbus-cleanup-sockets.1
debian/tmp/usr/share/dbus-1/services
debian/tmp/usr/share/dbus-1/system-services
debian/tmp/usr/share/man/man1/dbus-send.1
debian/tmp/usr/share/man/man1/dbus-uuidgen.1
debian/tmp/usr/share/man/man1/dbus-monitor.1
debian/tmp/lib/systemd/system/dbus.service
debian/tmp/lib/systemd/system/dbus.socket
debian/tmp/lib/systemd/system/dbus.target.wants/dbus.socket
debian/tmp/lib/systemd/system/multi-user.target.wants/dbus.service
debian/tmp/lib/systemd/system/sockets.target.wants/dbus.socket
