#!/bin/sh

set -e

if [ "$1" = "purge" ] ; then
	for bus in system session; do
		rm -f "/etc/dbus-1/${bus}.conf"
	done

	rmdir /var/run/dbus || true

	rm -f /var/lib/dbus/machine-id
	rmdir /var/lib/dbus || true

	LAUNCHER=/usr/lib/dbus-1.0/dbus-daemon-launch-helper

	if dpkg-statoverride --list "$LAUNCHER" >/dev/null 2>&1 ; then
		dpkg-statoverride --remove "$LAUNCHER"
	fi
fi

#DEBHELPER#

exit 0
